# template for server
app:
  host-url: http://localhost
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${PG_DATABASE:jira}-test
    username: ${PG_USERNAME:jira}
    password: ${PG_PASSWORD:JiraRush}